[mgr]
prepend_keymap = [
	{ on = [ "g", "c" ],       run = "cd ~/dotfiles/.config", desc = "Go ~/dotfiles/.config" },
	{ on = ["!"],       run = 'shell "$SHELL" --block ll', desc = "Open $Shell here" },

]

append_keymap = [
	{ on = [ "g", "b" ],       run = "cd ~/Bugs",             desc = "Go ~/Bugs" },
	{ on = [ "g", "r" ],       run = "cd ~/Bugs/Rosjects",    desc = "Go ~/Bugs/Rosjects" },
	{ on = [ "g", "p" ],       run = "cd ~/Bugs/PythonWorks", desc = "Go ~/Bugs/PythonWorks" },
	{ on = [ "g", "C" ],       run = "cd ~/Bugs/Cpp",         desc = "Go ~/Bugs/Cpp" },

	{ on = [ "T" , "a"],       run = "shell --orphan --confirm alacritty &",desc = "Open Alacritty" },
]

