[mgr]
prepend_keymap = [
	{ on = [ "g", "c" ],       run = "cd ~/dotfiles/.config", desc = "Go ~/dotfiles/.config" },
	{ on = ["!"],       run = 'shell "$SHELL" --block ll', desc = "Open $Shell here" },

]

append_keymap = [
	{ on = [ "g", "b" ],       run = "cd ~/Bugs",             desc = "Go ~/Bugs" },
	{ on = [ "g", "r" ],       run = "cd ~/Bugs/rosjects",    desc = "Go ~/Bugs/rosjects" },
	{ on = [ "g", "p" ],       run = "cd ~/Bugs/pythonWorks", desc = "Go ~/Bugs/pythonWorks" },
	{ on = [ "g", "C" ],       run = "cd ~/Bugs/cpp",         desc = "Go ~/Bugs/cpp" },

	{ on = [ "T" , "a"],       run = "shell --orphan --confirm alacritty &",desc = "Open Alacritty" },
	{ on = [ "T" , "g"],       run = "shell --orphan --confirm ghostty &",desc = "Open Ghostty" },
]

