services:
  python_ml_dev_env:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        UID: 1000
        USER: ubuntu
    image: python_ml_dev_env
    container_name: python_ml_dev_env_cont
    network_mode: host
    user: ubuntu
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /home/fayez/Bugs/PythonWorks/:/home/ubuntu/Bugs/PythonWorks/:rw
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/fonts/:/usr/share/fonts/
    tty: true
    command: "/bin/bash"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
