[general]
import = ["/home/fayez/.config/alacritty/themes/palenight.toml"]

[window]
opacity = 0.95
decorations = "None"

[font]
size = 11.5

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window.dimensions]
columns = 110
lines = 27

