[general]
import = ["/home/fayez/.config/alacritty/themes/palenight.toml"]

[font]
size = 11

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[window]
opacity = 0.75

[window.dimensions]
columns = 105
lines = 25
