[general]
import = ["/home/fayez/.config/alacritty/themes/catppuccin_macchiato.toml"]

[window]
opacity = 0.95

[window.dimensions]
columns = 125
lines = 37

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

