[general]
import = ["/home/fayez/.config/alacritty/themes/catppuccin_macchiato.toml"]

[window]
opacity = 0.95

[window.dimensions]
columns = 125
lines = 37

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

